### PR TITLE
Support setting progress

### PR DESCRIPTION
**Pull request by theodorejb**
* Added support for setting progress by binding to a number
* Fixed error when using the Rollup module bundler (with commonjs plugin)
* Fixed "Can't resolve all parameters for LaddaConfig" error when using the Angular 4 AOT compiler
* Enabled validation and code completion when setting a default style
* Simplified and optimized code for reading attributes and applying default styles

### CODE REVIEW

**Comment by theodorejb** [comment]
After merging this, be sure to delete any previously generated index.js, index.d.ts, etc. files from the project root before publishing to npm.

**Comment by theodorejb** [comment]
@moff Can you review this when you get a chance? It might be easiest to review the commits individually. Let me know if you have any questions.

**Comment by theodorejb** [comment]
@moff Do you have time to review this? It adds support for setting progress percentages, and also makes it possible to use the package with the Rollup module bundler and Angular 4. I can answer any questions you have about the commits.

If you aren't able to maintain this package anymore, would you be open to adding me as a contributor? The package has a lot of users, so I feel it's important to keep it up-to-date to support current tooling.

Thanks!

**Comment by moff** [comment]
Hi @theodorejb !

I've been traveling for about a month and it will take about a month more. So I don't have time to maintain this package now, but I'll be back after some time.

Contact me via email

Thank you for great job you're doing and sure I'll add you as a collaborator!

**Pull request closed without merging**
