### PR TITLE
Ahead-of-time compilation support

### PR DESCRIPTION
**Pull request by theodorejb**
* Removed typings dependency and enabled noImplicitAny
* Improved app home component so clicking buttons starts spinner
* Added support for ahead-of-time compilation usage

### CODE REVIEW

**Comment by theodorejb** [comment]
@moff Any chance you could review this soon? If not, I'd like to publish my fork to npm so we (and others) can start using Ladda in our AOT apps. Let me know if you have any questions about this pull request or notice changes that should be made.

**Comment by moff** [comment]
Hi, @theodorejb!

I'm traveling at the moment so I don't have time for checking my repos and I don't follow Angular updates for few monthes already so maybe I don't know about new stuff. I've reviewed your pull request and have some questions before I'll merge it:
1) Why have you removed typings, was it really necessary to do so?
2) Why have you deleted "exclude" part in tsconfig.json? I don't think we need folders mentioned in it to be in a package.

Thank you for your contribution!

**Comment by theodorejb** [comment]
Thanks for the review, @moff.

It wasn't technically necessary to remove the typings dependency, but it isn't needed anymore now that types can be installed via npm (I added the @types/core-js, @types/jasmine, and @types/node npm dependencies). Using npm eliminates the extra step of having to run `typings install`.

I deleted the "exclude" property in tsconfig.json because it didn't have any effect. The only included files are those specified by the "files" property, and [per the TypeScript documentation](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details) 'files included explicitly using the "files" property are always included regardless of "exclude".'

**Comment by moff** [comment]
Ok, got that.

Thank you for your contribution @theodorejb 

I'll push updated package to NPM asap.

**Pull request merged**
